<?php

use Drupal\Core\Form\FormBase;
use Drupal\Core\Form\FormStateInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\taxonomy\Entity\Term;
use Drupal\file\Entity\File;
use Drupal\Core\Database\Connection;
use \Drupal\user\Entity\User;
use Drupal\node\Entity\Node;

/**
 * Implementation of hook_theme
 *
 * @param [type] $existing
 * @param [type] $type
 * @param [type] $theme
 * @param [type] $path
 * @return void
 */
function user_profile_data_theme($existing, $type, $theme, $path) {
  return array(
    'custom_user_profile_block_template' => array(
      'variables' => array('output' => NULL),
      'template' => 'custom-user-profile-block-template',
    ),
  );
}